### PR TITLE
code style cleanup (no functional changes).

### PR DESCRIPTION
**Pull request by rubensayshi**
most of it is done automated (PHPStorm code format). 
a lot of 4spaces (and even tabs) being replaced, 
in general missing spaces between `if(` and params etc.

doesn't hurt to keep it clean imo and it was hurting my eyes when working on stuff :stuck_out_tongue:

### CODE REVIEW

**Comment by rubensayshi** [comment]
scanning through the diff now myself to see if anything odd happened, but shouldn't have

**Comment by robby-dermody** [comment]
@rubensayshi  I'm fine with this, except that the reformating should exclude the following files:
```src/js/external/mnemonic.js
src/js/external/qrcode.js
src/js/smartadmin.app.js```

Reason being, these come from external sources and I'd rather have their original formatting so they can be more easily diffed to the original (especially `mnemonic.js`, since it is such an important file to be secure)

**Comment by rubensayshi** [comment]
I completely agree, I redid the reformatting a few times, must have excidently touched those too during the final attempt.

**Comment by robby-dermody** [comment]
Close, can you also remove `src/js/smartadmin.app.js` as well? (that file was originally copied from the smartadmin admin template counterwallet uses, and I like to be able to easily diff it for when we upgrade smartadmin).

**Pull request merged**
