### PR TITLE
Fix #627 - git warning about timeago i18n file

### LINKED ISSUE #627: git warns about changes to src/js/jquery-timeago.i18n.js that I didn't make
I ran into this while rebuilding Fed Node with v9.49.3 from (d)evelop using Counterwallet and (B)oth. 
Should this be filed under `counterpartyd_build` perhaps?

```
2014-12-31 13:51:54,194|DEBUG: RUNNING COMMAND: cd /home/xcp/counterwallet && git pull origin develop
From https://github.com/CounterpartyXCP/counterwallet
 * branch            develop    -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
        src/js/jquery-timeago.i18n.js
Please, commit your changes or stash them before you can merge.
Aborting
2014-12-31 13:51:56,182|ERROR: Command failed: 'cd /home/xcp/counterwallet && git pull origin develop'
```

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/7410468-git-warns-about-changes-to-src-js-jquery-timeago-i18n-js-that-i-didn-t-make?utm_campaign=plugin&utm_content=tracker%2F542579&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F542579&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by digital-dreamer**
jquery-timeago.i18n.js is generated by Grunt (from the js files in vendors/jquery-timego), based on language settings. It should not be included in the repository, because otherwise git will show warnings about local changes.

I also put it in .gitignore to prevent a locally generated file from being commited - this is what happened in 60cf658d22942348455afd3afc69f4747a771f87

Fixes #627

### CODE REVIEW

**Comment by rippler** [comment]
Just installed Fed Node (`(U)pdate`d from Master after @ouziel-slama released it)

```
Successfully installed gevent geventhttpclient grequests
Cleaning up...
2015-01-06 08:46:14,837|INFO: counterpartyd config file already exists at: '/home/xcp/.config/counterpartyd/counterpartyd.conf'
2015-01-06 08:46:14,837|INFO: counterblockd config file already exists at: '/home/xcp/.config/counterblockd/counterblockd.conf'
2015-01-06 08:46:14,837|INFO: SETUP DONE. (It's time to kick ass, and chew bubblegum... and I'm all outta gum.)
2015-01-06 08:46:14,850|INFO: Checking out/updating counterwallet:master from git...
2015-01-06 08:46:14,850|DEBUG: RUNNING COMMAND: cd /home/xcp/counterwallet && git pull origin master
From https://github.com/CounterpartyXCP/counterwallet
 * branch            master     -> FETCH_HEAD
Updating 78e6bbd..3e2f0bc
error: Your local changes to the following files would be overwritten by merge:
        src/js/jquery-timeago.i18n.js
Please, commit your changes or stash them before you can merge.
Aborting
2015-01-06 08:46:15,011|ERROR: Command failed: 'cd /home/xcp/counterwallet && git pull origin master'

```

**Comment by digital-dreamer** [comment]
@rippler - your installation was in a broken state where you couldn't automatically pull anything from counterwallet repository, not even the patch that was just released. But I see you already figured out how to resolve this.

**Comment by rippler** [comment]
@digital-dreamer - I believe you, but I interfaced with using the official install scripts. At the same time time I know I didn't follow best practices, because it's a test system. I'll make changes to the docs.

**Comment by digital-dreamer** [comment]
Good idea, you could add this to the troubleshooting section - what to do when a user gets the message that you saw during installation. A universal solution would be to go to the damaged project's folder (in this case /home/xcp/counterwallet) and issue `git reset --hard` This will discard any local changes to the files included in the repository (returning them to the state of the last commit), but won't affect files that are not tracked by git (so your counterwallet.conf.json will be preserved).

**Comment by rippler** [comment]
Done (on Support site, KB articles)

**Pull request merged**
